routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::Resource('pokemons', 'PokemonController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]);

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PokemonController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePokemonRequest;
use App\Http\Requests\UpdatePokemonRequest;
use App\UseCases\DestroyPokemonUseCase;
use App\UseCases\ListPokemonUseCase;
use App\UseCases\StorePokemonUseCase;
use App\UseCases\UpdatePokemonUseCase;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class PokemonController extends Controller
{
    public function index(Request $request, ListPokemonUseCase $useCase) {
        return $useCase->handle($request->get('page', 1));
    }

    public function create() {
        return view('pokemons.create');
    }

    public function store(StorePokemonRequest $request, StorePokemonUseCase $useCase) {
        $useCase->handle($request->all());
        return redirect(route('pokemons.index'));
    }

    public function edit(Request $request) {
        $fileContent = Storage::get('pokemon.csv');
        $arrayRows = explode("\n", $fileContent);

        $collection = collect();
        foreach ($arrayRows as $index => $row) {
            $arrayCells = str_getcsv($row);
            if($request->pokemon == $arrayCells[0]) {
                $collection->add($arrayCells);
                break;
            }
        }

        return view('pokemons.edit', ['pokemon' => $collection->first()]);
    }

    public function update(UpdatePokemonRequest $request, UpdatePokemonUseCase $useCase) {
        $data = array_merge(['id' => $request->pokemon], $request->all());
        $useCase->handle($data);
        return redirect(route('pokemons.index'));
    }

    public function destroy(Request $request, DestroyPokemonUseCase $useCase) {
        $useCase->handle(['id' => $request->pokemon]);//Id is pass through the Resource.

        return redirect()->back();
    }
}

resources/views/pokemons/create.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Create pokemon</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Create a pokemon
                    @if($errors)
                        @foreach ($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    @endif
                    <div>
                        <form action="{{route('pokemons.store')}}" method="POST">
                            @csrf
                            <div>
                                <label for="no">No</label>
                                <input id="no" name="no" type="text" >
                            </div>

                            <div>
                                <label for="name">Name</label>
                                <input id="name" name="name" type="text">
                            </div>
                            <div>
                                <label for="type_1">Type 1</label>
                                <input id="type_1" name="type_1" type="text">
                            </div>
                            <div>
                                <label for="type_2">Type 2</label>
                                <input id="type_2" name="type_2" type="text">
                            </div>
                            <div>
                                <label for="total">Total</label>
                                <input id="total" name="total" type="text">
                            </div>
                            <div>
                                <label for="hp">HP</label>
                                <input id="hp" name="hp" type="text">
                            </div>
                            <div>
                                <label for="attack">Attack</label>
                                <input id="attack" name="attack" type="text">
                            </div>
                            <div>
                                <label for="defense">Defense</label>
                                <input id="defense" name="defense" type="text">
                            </div>
                            <div>
                                <label for="sp_atk">Sp. Atk</label>
                                <input id="sp_atk" name="sp_atk" type="text">
                            </div>
                            <div>
                                <label for="sp_def">Sp. Def</label>
                                <input id="sp_def" name="sp_def" type="text">
                            </div>
                            <div>
                                <label for="speed">Speed</label>
                                <input id="speed" name="speed" type="text">
                            </div>
                            <div>
                                <label for="generation">Generation</label>
                                <input id="generation" name="generation" type="text">
                            </div>
                            <div>
                                <label for="legendary">Legendary</label>
                                <select id="legendary" name="legendary">
                                    <option value="0">False</option>
                                    <option value="1">True</option>
                                </select>
                            </div>
                            <button type="submit" >Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/pokemons/edit.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Edit pokemon</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

</head>
<body>
<div class="flex-center position-ref full-height">
    @if (Route::has('login'))
        <div class="top-right links">
            @auth
                <a href="{{ url('/home') }}">Home</a>
            @else
                <a href="{{ route('login') }}">Login</a>

                @if (Route::has('register'))
                    <a href="{{ route('register') }}">Register</a>
                @endif
            @endauth
        </div>
    @endif

    <div class="content">
        <div class="title m-b-md">
            Edit a pokemon
            @if($errors)
                @foreach ($errors->all() as $error)
                    <div>{{ $error }}</div>
                @endforeach
            @endif
            <div>
                <p>Id : {{ $pokemon[0] }}</p>
                <form action="{{route('pokemons.update', [$pokemon[0]])}}" method="POST">
                    <input name="_method" type="hidden" value="PUT">
                    @csrf
                    <div>
                        <label for="no">No</label>
                        <input id="no" name="no" type="text" value={{ $pokemon[1] }}>
                    </div>

                    <div>
                        <label for="name">Name</label>
                        <input id="name" name="name" type="text" value={{ $pokemon[2] }}>
                    </div>
                    <div>
                        <label for="type_1">Type 1</label>
                        <input id="type_1" name="type_1" type="text" value={{ $pokemon[3] }}>
                    </div>
                    <div>
                        <label for="type_2">Type 2</label>
                        <input id="type_2" name="type_2" type="text" value={{ $pokemon[4] }}>
                    </div>
                    <div>
                        <label for="total">Total</label>
                        <input id="total" name="total" type="text" value={{ $pokemon[5] }}>
                    </div>
                    <div>
                        <label for="hp">HP</label>
                        <input id="hp" name="hp" type="text" value={{ $pokemon[6] }}>
                    </div>
                    <div>
                        <label for="attack">Attack</label>
                        <input id="attack" name="attack" type="text" value={{ $pokemon[7] }}>
                    </div>
                    <div>
                        <label for="defense">Defense</label>
                        <input id="defense" name="defense" type="text" value={{ $pokemon[8] }}>
                    </div>
                    <div>
                        <label for="sp_atk">Sp. Atk</label>
                        <input id="sp_atk" name="sp_atk" type="text" value={{ $pokemon[9] }}>
                    </div>
                    <div>
                        <label for="sp_def">Sp. Def</label>
                        <input id="sp_def" name="sp_def" type="text" value={{ $pokemon[10] }}>
                    </div>
                    <div>
                        <label for="speed">Speed</label>
                        <input id="speed" name="speed" type="text" value={{ $pokemon[11] }}>
                    </div>
                    <div>
                        <label for="generation">Generation</label>
                        <input id="generation" name="generation" type="text" value={{ $pokemon[12] }}>
                    </div>
                    <div>
                        <label for="legendary">Legendary</label>
                        <select id="legendary" name="legendary">
                            <option value="0" {{$pokemon[13] == 0 ? 'selected' : ''}} >False</option>
                            <option value="1" {{$pokemon[13] == 1 ? 'selected' : ''}}>True</option>
                        </select>
                    </div>
                    <button type="submit" >Edit</button>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

resources/views/pokemons/index.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Api test Pokemon</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

</head>
<body>
<div class="flex-center position-ref full-height">
    @if (Route::has('login'))
        <div class="top-right links">
            @auth
                <a href="{{ url('/home') }}">Home</a>
            @else
                <a href="{{ route('login') }}">Login</a>

                @if (Route::has('register'))
                    <a href="{{ route('register') }}">Register</a>
                @endif
            @endauth
        </div>
    @endif

    <div class="content">
        <div class="title m-b-md">
            Pokemon Index
        </div>

        <div class="links">
            <a href="{{ route('pokemons.create') }}">Create</a>
            <table>
                <tr>
                    <th>Id</th>
                    <th>No</th>
                    <th>Name</th>
                    <th>Type 1</th>
                    <th>Type 2</th>
                    <th>Total</th>
                    <th>HP</th>
                    <th>Attack</th>
                    <th>Defense</th>
                    <th>Sp. Atk</th>
                    <th>Sp. Def</th>
                    <th>Speed</th>
                    <th>Generation</th>
                    <th>Legendary</th>
                </tr>

            @foreach($collection as $pokemon)

                <tr>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 0)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 1)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 2)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 3)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 4)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 5)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 6)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 7)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 8)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 9)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 10)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 11)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 12)}}</td>
                    <td>{{\Illuminate\Support\Arr::get($pokemon, 13)}}</td>
                    <td><a href="{{ route('pokemons.edit', [$pokemon[0]]) }}">Edit</a></td>
                    <td>
                        <form action="{{ route('pokemons.destroy', [$pokemon[0]]) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" >Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </table>
            @if($pageIndex > 1)
                <a href="{{ route('pokemons.index').'?page='.($pageIndex-1) }}" >Previous</a>
            @endif
            @if($pageIndex < $pageCount)
                <a href="{{ route('pokemons.index').'?page='.($pageIndex+1) }}" >Next</a>
            @endif
        </div>
    </div>
</div>
</body>
</html>